FROM quay.io/sampandey001/secktor
RUN git clone https://github.com/CyberWarriorsX/FORZEN-MD /root/CyberWarriorsX
WORKDIR /root/CyberWarriorsX/
RUN npm install npm@latest
EXPOSE 8000
CMD ["npm", "start"]
